name: Deploy Website
on: 
  push:
    branches:
      - main
jobs:
  test:
    environment: QA
    env:
      env_vars: ${{ vars.QA_VARS }}
    runs-on: ubuntu-latest
    steps:
      - name: output env vars
        run: |
          echo "env vars of QA is : ${{ env.env_vars }} "
      - name: Get Code -checkout
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get Code -checkout
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-file::{}' ';'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
         
  deploy:
    environment: prod
    needs: build
    env:
      GLOBAL: ${{ vars.GLOBAL }}
      env_vars: ${{ vars.PROD_VARS }}
    runs-on: ubuntu-latest
    steps:
      - name: output env vars
        run: |
          echo "env vars of PROD is : ${{ env.env_vars }} "
      - name: Get Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: output contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: deploy
        run: echo "Deploying ..."
      - name: Output Information
        run: |
          echo "Global var: ${{ env.GLOBAL }}"
